Feature send fragment configuration v1.0.0
AlexDlaTorre/bankodemia pull request #38
Opened 2022-03-27 03:02 UTC by AlexDlaTorre

Contacts recyclerview configuration on send fragment

2022-03-27 23:52 UTC, jpgpineda requested changes
Todo muy bien Ale. Nada mas te dejo el comment de la interfaz

2022-03-27 23:52 UTC, jpgpineda commented on app/src/main/java/com/example/bankodemia/ui/adapters/ContactsAdapter.kt
> +    fun <T>ItemSelected(item: T)
Ale esa interfaz ya esta definida en TransactionsAdapter. Ya no es necesario que la vuelvas definir aqui

2022-03-28 00:13 UTC, AlexDlaTorre commented on app/src/main/java/com/example/bankodemia/ui/adapters/ContactsAdapter.kt
> +    fun <T>ItemSelected(item: T)
ok, ahorita lo quito

2022-03-28 02:00 UTC, AlexDlaTorre commented on app/src/main/java/com/example/bankodemia/ui/adapters/ContactsAdapter.kt
> +    fun <T>ItemSelected(item: T)
Listo, ya lo eliminé

2022-03-28 02:59 UTC, jpgpineda approved these changes

2022-03-28 03:24 UTC, JoseSom approved these changes

2022-03-28 03:26 UTC, merged