[BAN-18][BAN-21](2)[BAN-23][BAN-35] Flujo Completo Create Account
AlexDlaTorre/bankodemia pull request #44
Opened 2022-04-02 07:18 UTC by JoseSom

- Se implementa flujo completo de create account

https://user-images.githubusercontent.com/75000816/161371706-8f7d0f32-d66f-4d23-a281-9ab8c839658c.mp4

- Se implementa el guardado automtico de los campos de datos para create account

https://user-images.githubusercontent.com/75000816/161371742-5e08ee04-4ffd-44fe-8418-50a5ffb0ff2f.mp4

- Se implementa el manejo de errores para create account

https://user-images.githubusercontent.com/75000816/161371758-5ed2e890-ebe8-4adf-a68b-44058f14215f.mp4

- Se modifican el navigation para cerrar los contra flujos para no crear bucles

2022-04-02 19:29 UTC, AlexDlaTorre approved these changes
Muy buen trabajo

2022-04-02 23:54 UTC, jpgpineda requested changes

2022-04-02 23:54 UTC, jpgpineda commented on app/src/main/java/com/example/bankodemia/ui/view/TelephoneFragment.kt
> +        val ladaFormat = if (lada.length <= 2 || lada.contains("+")) lada else lada.substring(0,2)
Aqui puedes usar las extensiones de Int que creamos. Seria Int.two, Int.zero. Igual se puede crear una extension de String para el simbolo de "+". Seria algo como esto: String.Companion.aditionSymbol

2022-04-02 23:54 UTC, jpgpineda commented on app/src/main/java/com/example/bankodemia/ui/view/TelephoneFragment.kt
> +        val telephoneFormat = if (ladaFormat.contains("+")) "$ladaFormat$telephone" else "+$ladaFormat$telephone"
Igual aqui puedes usar el String.Companion.aditionSymbol. Lo creas y lo llamas asi: String.aditionSymbol

2022-04-04 14:33 UTC, jpgpineda approved these changes

2022-04-04 14:49 UTC, merged